### PR TITLE
Suggested-resolution-issue-45 (Re-order of principles subsections)

### PR DESCRIPTION
**Pull request by mirjak**
as proposed in issue #45

### CODE REVIEW

**Review by jariarkko — APPROVED** [review]
I don't have a big preference either way, but am ok with this.

**Review by tfpauly — APPROVED** [review]

**Comment by tfpauly** [comment]
I also don't have a strong preference, but this seems fine.

**Comment by mirjak** [comment]
I also don't have a really strong opinion but at my last full read I thought this order might flow better (also because of some cross references within the section). I believe so far the order was mostly random, and now it might reflect a bit better the interconnections between the subsections. But I guess it mostly a matter of taste...

**Comment by jariarkko** [comment]
This PR had gone out of date; its effect was manually applied. Closing the PR.

**Pull request closed without merging**
